http_server:
  host: "localhost"
  port: 8080
  timeout: 6
  idle_timeout: 60
url_database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "urldb"
  ssl: "disable"
user_database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "urldb"
  ssl: "disable"